### PR TITLE
Punkt: expose custom variables on object instances

### PR DESCRIPTION
**Pull request by mikehenrty**
I was very excited to discover this JS implementation of Punkt. Thanks for building it!

Using your library I'd like to do the following, but it seems the current implementation won't allow configuring custom variables:

```Python
# In Python...
trainer = PunktTrainer()
trainer.INCLUDE_ALL_COLLOCS = True
trainer.train(text)
```

I think a good way to conform to the original python API would be to expose these on the instance objects in the constructor. I've taken a shot at this in the PR. Let me know what you think.

### CODE REVIEW

**Comment by Yomguithereal** [comment]
Thanks @mikehenrty. This is not my preferred solution but it's good enough so I think I will merge. My original intention was to make all this more JavaScripty in feel but I did not find the time.

**Comment by Yomguithereal** [comment]
Do you need a release on npm?

**Comment by mikehenrty** [comment]
> Do you need a release on npm?

Yes please :)

Thanks again @Yomguithereal !

**Comment by Yomguithereal** [comment]
v0.21.0 is now published.

**Comment by mikehenrty** [comment]
cheers

**Pull request merged**
